# Generated by Django 2.0.1 on 2018-01-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.CharField(max_length=20, verbose_name='Альбом')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=20, verbose_name='Жанр')),
            ],
        ),
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musician', models.CharField(max_length=20, verbose_name='Исполнитель')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.CharField(max_length=25, verbose_name='Песня')),
                ('lyrics', models.TextField(blank=True, null=True, verbose_name='Текст песни')),
                ('album', models.ForeignKey(on_delete='CASCADE', to='discography.Album', verbose_name='Альбом')),
                ('genre', models.ForeignKey(on_delete='CASCADE', to='discography.Genre', verbose_name='Жанр')),
                ('musician', models.ForeignKey(on_delete='CASCADE', to='discography.Musician', verbose_name='Исполнитель')),
            ],
        ),
    ]
