# Generated by Django 2.0.1 on 2018-01-12 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discography', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ('album',), 'verbose_name': 'Альбом', 'verbose_name_plural': 'Альбомы'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ('genre',), 'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterModelOptions(
            name='musician',
            options={'ordering': ('musician',), 'verbose_name': 'Исполнитель', 'verbose_name_plural': 'Исполнители'},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ('song',), 'verbose_name': 'Песня', 'verbose_name_plural': 'Песни'},
        ),
    ]
