# Generated by Django 2.0.1 on 2018-01-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discography', '0002_auto_20180112_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='lyrics_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Текст песни'),
        ),
    ]
