# Generated by Django 2.0.1 on 2018-01-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discography', '0003_song_lyrics_ru'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ('musician',), 'verbose_name': 'Песня', 'verbose_name_plural': 'Песни'},
        ),
        migrations.AlterField(
            model_name='song',
            name='lyrics_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Текст песни на русском'),
        ),
    ]
