# Generated by Django 2.0.1 on 2018-01-17 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discography', '0004_auto_20180114_0618'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'verbose_name': 'Альбом', 'verbose_name_plural': 'Альбомы'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterModelOptions(
            name='musician',
            options={'verbose_name': 'Исполнитель', 'verbose_name_plural': 'Исполнители'},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'verbose_name': 'Песня', 'verbose_name_plural': 'Песни'},
        ),
        migrations.RenameField(
            model_name='album',
            old_name='album',
            new_name='album_name',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='genre',
            new_name='genre_name',
        ),
        migrations.RenameField(
            model_name='musician',
            old_name='musician',
            new_name='musician_name',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='song',
            new_name='song_name',
        ),
    ]
