# Generated by Django 2.0.1 on 2018-01-20 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discography', '0007_musician_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='image',
            field=models.ImageField(blank=True, height_field=100, null=True, upload_to='', verbose_name='Изображение исполнителя', width_field=100),
        ),
    ]
