# Generated by Django 2.0.1 on 2018-01-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discography', '0010_remove_musician_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_name',
            field=models.CharField(max_length=25, verbose_name='Альбом'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre_name',
            field=models.CharField(max_length=25, verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='musician',
            name='musician_name',
            field=models.CharField(max_length=25, verbose_name='Исполнитель'),
        ),
    ]
