# Generated by Django 2.0.1 on 2018-01-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discography', '0005_auto_20180117_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.ForeignKey(on_delete='CASCADE', related_name='album_songs', to='discography.Album', verbose_name='Альбом'),
        ),
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.ForeignKey(on_delete='CASCADE', related_name='genre_songs', to='discography.Genre', verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='song',
            name='musician',
            field=models.ForeignKey(on_delete='CASCADE', related_name='musician_songs', to='discography.Musician', verbose_name='Исполнитель'),
        ),
    ]
