# Generated by Django 2.0.1 on 2018-01-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discography', '0006_auto_20180118_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='information',
            field=models.TextField(blank=True, null=True, verbose_name='Информация'),
        ),
    ]
