# Generated by Django 2.0.1 on 2018-01-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discography', '0008_musician_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение исполнителя'),
        ),
    ]
