# Generated by Django 2.0.1 on 2018-01-20 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discography', '0009_auto_20180120_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musician',
            name='image',
        ),
    ]
