# Generated by Django 2.0.1 on 2018-01-21 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discography', '0011_auto_20180121_2244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='album_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='genre_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='musician',
            old_name='musician_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='song_name',
            new_name='name',
        ),
    ]
